teal.goshawk vignette
insightsengineering/teal.goshawk pull request #195
Opened 2022-10-07 14:41 UTC by nikolas-burkoff

2022-10-07 15:24 UTC, pawelru commented on vignettes/sample-app.Rmd
> +```{r, eval = FALSE}
We have a separate repo for sample apps. I would push on publicising it soon. 
Other than that - this is not a good idea to have a big chunk of code that is not being tested. It asks to be outdated soon. Typical agile-r mistake as we know. 

Therefore I would recommend to remove this file (with all of its references) and wait for teal.gallery to be public.

2022-10-11 16:05 UTC, asbates requested changes

2022-10-11 18:01 UTC, asbates approved these changes

2022-10-11 18:19 UTC, pawelru commented
closes #194

2022-10-11 22:08 UTC, donyunardi approved these changes

2022-10-11 22:08 UTC, merged