198 Include user's card labels when generating the report
insightsengineering/teal.goshawk pull request #241
Opened 2023-10-04 13:44 UTC by kartikeyakirar

this PR fixes https://github.com/insightsengineering/teal.goshawk/issues/240

this is follow-up after https://github.com/insightsengineering/teal.reporter/pull/219

2023-10-06 08:07 UTC, kartikeyakirar commented
CMD checks are failing because of  `mcr` package is archived from CRAN

2023-10-06 13:40 UTC, m7pr commented
@kartikeyakirar please take out card_template and move it to teal.reporter.
https://github.com/insightsengineering/teal.modules.general/pull/584#issuecomment-1750699411

2023-10-06 13:40 UTC, m7pr commented
@kartikeyakirar please take out card_template and move it to teal.reporter.
https://github.com/insightsengineering/teal.modules.general/pull/584#issuecomment-1750699411

2023-10-12 10:06 UTC, m7pr requested changes
please append teal:: before report_card_template so it's easier for debugging in the future

2023-10-12 10:06 UTC, m7pr commented on R/tm_g_gh_boxplot.R
> +        card <- report_card_template(
```suggestion
        card <- teal::report_card_template(
```

2023-10-12 10:06 UTC, m7pr commented on R/tm_g_gh_boxplot.R
> +        card <- report_card_template(
cc @kartikeyakirar and there is more than one place for this

2023-10-12 10:08 UTC, m7pr requested changes

2023-10-12 10:08 UTC, m7pr commented on R/utils.R
> +report_card_template <- function(title,
@kartikeyakirar this is not a good idea to have the same name of the function in 2 packages. Please rename to `report_card_template_goshawk`

2023-10-12 10:08 UTC, m7pr commented on R/tm_g_gh_boxplot.R
> +        card <- report_card_template(
ok it looks like it is a wrapper provided in teal.goshawk. You see how this name was confusing for me as it is the same as in teal. So please follow my advise from https://github.com/insightsengineering/teal.goshawk/pull/241#discussion_r1356596742

2023-10-12 10:11 UTC, kartikeyakirar commented
@m7pr  there is no namesapce call because  its internal function I have defined `report_card_template` here in the `utils`, and it makes use of `teal::report_card_template`. https://github.com/insightsengineering/teal.goshawk/blob/198_card_labels%40main/R/utils.R#L35-L79

2023-10-12 10:14 UTC, m7pr commented
> CMD checks are failing because of mcr package is archived from CRAN
Is back on CRAN

2023-10-12 10:15 UTC, kartikeyakirar commented on R/tm_g_gh_boxplot.R
> +        card <- report_card_template(
https://github.com/insightsengineering/teal.goshawk/pull/241#issuecomment-1759322644

2023-10-12 13:10 UTC, m7pr commented
https://github.com/insightsengineering/teal.goshawk/pull/241#discussion_r1356597506

2023-10-12 13:13 UTC, m7pr approved these changes

2023-10-12 13:15 UTC, m7pr requested changes

2023-10-12 13:15 UTC, m7pr commented on R/utils.R
> +#' Template function to generate reporter card for `teal.goshawk`
@kartikeyakirar this is a title of RD file. Can you make it TITLE case . Can you use the same structure of teal? https://github.com/insightsengineering/teal/pull/933#discussion_r1356494205 Why am I making the same advise twice?

2023-10-12 13:42 UTC, kartikeyakirar commented on R/utils.R
> +#' Template function to generate reporter card for `teal.goshawk`
There was oversight. sorry about that.

2023-10-12 13:47 UTC, m7pr approved these changes

2023-10-13 09:57 UTC, merged